### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by ferradeira** [ZeXtras/universal-dialer#8]
Hi,
I'm running Zimbra 8.7.11.
After copy zal.jar file, cp /tmp/zal.jar /opt/zimbra/lib/ext/universalDialer/, get it from 
wget http://openzal.org.s3.amazonaws.com/1.11/zal-1.11.13-8.7.11.jar -O /tmp/zal.jar
and zmcontrol restart
when I access the zimbra admin I get a blank page.
Any idea?

**Comment by StefanoGrasselli** [comment]
Take a look at /opt/zimbra/log/mailbox.log, I expect an error logged there.
Try to add also asterisk-java-1.0.0-m1.jar library to /opt/zimbra/lib/ext/universalDialer/.

**Comment by ferradeira** [comment]
This is what I have in /opt/zimbra/lib/ext/universalDialer
-rw-r--r-- 1 root root   34222 Jul 11 10:09 asterisk-java-1.0.0-m1.jar
-rw-r--r-- 1 root root   12792 Jul 11 10:10 universal-dialer-extension.jar
-rw-r--r-- 1 root root 1070679 Jul 21 14:35 zal.jar

What happens when I run:
$ zmprov fc all
ERROR: service.PROXY_ERROR (error while proxying request to target server: HTTP/1.1 503 Service Unavailable)

mailbox.log:
2017-07-21 14:47:13,811 ERROR [qtp127618319-51:https:https://zimbra.domain.pt:7071/zimbraAdmin/] [] webclient - Unable to get domain config
com.zimbra.common.service.ServiceException: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
ExceptionId:qtp127618319-51:https:https://zimbra.domain.pt:7071/zimbraAdmin/:1500644833798:1438e286dd60b40f
Code:service.PROXY_ERROR Arg:(url, STR, "https://localhost:7071/service/admin/soap/AuthRequest")
        at com.zimbra.common.service.ServiceException.PROXY_ERROR(ServiceException.java:373)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:254)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:173)
        at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:419)
        at com.zimbra.common.soap.SoapTransport.invokeWithoutSession(SoapTransport.java:405)
        at com.zimbra.cs.account.soap.SoapProvisioning.invokeRequest(SoapProvisioning.java:449)
        at com.zimbra.cs.account.soap.SoapProvisioning.invoke(SoapProvisioning.java:457)
        at com.zimbra.cs.account.soap.SoapProvisioning.soapAdminAuthenticate(SoapProvisioning.java:401)
        at com.zimbra.cs.account.soap.SoapProvisioning.soapZimbraAdminAuthenticate(SoapProvisioning.java:429)
        at com.zimbra.cs.servlet.SetHeaderFilter.getResponseHeaders(SetHeaderFilter.java:109)
        at com.zimbra.cs.servlet.SetHeaderFilter.addZimbraResponseHeaders(SetHeaderFilter.java:96)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:82)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:258)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:58)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)

**Comment by StefanoGrasselli** [comment]
This error cannot be straightly connected to universal-dailer and can be a conseguence that something goes wrong at mailbox start; maybe universal-dialer doesn't start correctly ('zmmailboxdctl restart').

P.S.: I've noticed you have a shrinked version of asterisk-java-1.0.0-m1.jar (33KB), the 
recommended one has size 370KB

**Comment by ferradeira** [comment]
That's right, I did a bad download of the asterisk-java-1.0.0-m1.jar file.
I just copy the new downloaded file and zimbra is up.
In the user dialer settings, what should I use? Phone number is the extension number? and the Phone Pin is the password? I'm not sure of that. If I use the extension number ad the password I get User/Pin combination not found.
Thanks
